# Active profile — switch to prod for MySQL
spring.profiles.active=dev

# App name
spring.application.name=flopkart

# Thymeleaf
spring.thymeleaf.cache=false

# JPA common settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true